name: 'Client tests'

on:
  push:
    branches-ignore: [main]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Prettify Check
        run: npm run prettify-check
      - name: ESLint
        run: npm run lint
      - name: Build
        run: npm run build:ci
